model_name: resnet
# model options: resnet or vit

task: binary
# task options: binary or multiclass

# if binary, specify which classes are positive and negative
binary_setup:
  positive: ["accidental"]
  negative: ["normal", "paintings"]

balancing: none
# balancing options: none, sampler or weighted_loss


# for resnet preferred
training:
  epochs: 10
  batch_size: 32
  lr: 0.0001

# for vit preferred
# training:
#   epochs: 10
#   batch_size: 16
#   lr: 0.00003