model_name: resnet
# model options: resnet or vit

task: binary
# task options: binary or multiclass

# if binary, specify which classes are positive and negative
binary_setup:
  positive: ["accidental"]
  negative: ["normal"]

balancing: weighted_loss
# balancing options: none, sampler or weighted_loss


# for resnet preferred
training:
  epochs: 10
  batch_size: 10
  lr: 0.0001
  early_stopping_patience: 3
  early_stopping_min_delta: 0.001
  freeze_pretrained: true

# for vit preferred
# training:
#   epochs: 10
#   batch_size: 16
#   lr: 0.00003